---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/chaelrag/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp rago_resume.pdf $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH